= Cassandra Example

Example of running Cassandra locally with Docker, for use as demo and exercises in the DM566 course at IMADA, SDU.


== Build and run

=== Cassandra

Use Docker compose to startup cassandra cluster

 docker-compose up

To use the Cassandra Command Line Shell, enter one of the nodes in docker:

 docker exec -it cassandraexample_cassandra-node-1_1 bash

Once inside, use

 cqlsh

Now you can query the Cassandra database directly

 CREATE KEYSPACE demodb WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'datacenter1' : 3 };
 USE demodb;
 CREATE TABLE emp ( empID int, deptID int, first_name varchar,last_name varchar, PRIMARY KEY (empID, deptID));
 INSERT INTO emp (empID, deptID, first_name, last_name) VALUES (104, 15, 'jane', 'smith');

=== Application

Run using

 ./gradlew run

Available commands are:

* *load* Loads the Pokemon dataset
* *scan* Lists the pokemon with their name and type (Type1)
* *id* Asks which id of pokemon you will see. #42 is _Golbat_


== Pokemon Example Data

The dataset is from here: https://www.kaggle.com/shoduro/pick-your-pokemon/data

== Exercises

The code is in Groovy, but you can program JAVA if you prefer this. Very few JAVA constructs are invalid Groovy (Up to JAVA 7).

You should find help in the documentation and resources (see later section)

. Clone the repo, and try to run the code using `./gradlew run`
** Possible inputs are:
*** *create* Create the keyspace
*** *load* Loads the Pokemon dataset
*** *scan* Lists the pokemon
*** *destroy* Destroys the keyspace
*** *id* Asks which number of pokemon you will see. #42 is _Golbat_ - This is an exercise for you to get working

. Once you have run the application and the create and load tasks. Use a command line to go inside the cassandra cluster in docker and check the dta is there with the cqlsh tool
. Implement the *id* task
. Make the output format of the id task display prettier, and not just a printline of a pokemon type.
. Try to implement querying, so you can query by a type, and only gets pokemons of that type displayed.
** You might need to save the data in a new/additional way
. Add a seen column to the pokemon, and add a method where you can increment the number of times you have seen the different pokemons.
. Implement querying where you get listed all pokemons you have seen less times than/more times that a supplied number.
** Think of your datamodelling - should something be refactored?
. Add a delete method where you can remove a pokemon from the dataset
. Add information on where you have seen a pokemon, so you can get a list of all the places you have seen it
** Make also an aggegate list, where you group by the location.
. Extend the location with a username, so you can use the database for many users
** And extract who have seen the pokemon how many times.

TIP: There should be plenty of exercises - this is by design, so you don't run out of ideas to implement in the tutorial session.

== Resources

* http://www.baeldung.com/cassandra-with-java
* http://cassandra.apache.org/
* https://docs.datastax.com/en/cql/3.3/index.html
* https://docs.datastax.com/en/developer/java-driver/3.4/
